### ISSUE TITLE
New Name

### ISSUE THREAD

**Issue by andrew** [foragepm/forage#42]
The name forest clashes with some other things in the IPFS/Filecoin world, so needs to be something different. Ideas welcome, ideally have the npm name/org available.

**Comment by momack2** [comment]
I'm a fan of Gaelic - their words are beautiful. Ideas that build on forest: 
- coille
- foraoise
- crainn

**Comment by olizilla** [comment]
forage - _search widely for food or provisions_

...also looks a bit like _package_ and _for ages_

**Comment by andrew** [comment]
It is done, forest is now called Forage! https://github.com/foragepm/forage
